---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: fullstack
    run_list:
      - recipe[chef-server-cluster::standalone]
    driver:
      network:
        - ["private_network", {ip: "192.168.33.7"}]
    attributes:
      ec:
        couchdb:
          enable: true
        rabbitmq:
          enable: true
        postgresql:
          enable: true
        oc_bifrost:
          enable: true
        opscode_certificate:
          enable: true
        opscode_account:
          enable: true
        opscode_solr:
          enable: true
        opscode_expander:
          enable: true
        bookshelf:
          enable: true
        opscode_org_creator:
          enable: true
        opscode_erchef:
          enable: true
        opscode_webui:
          enable: true
